import 'normalize.css'
import './fonts.scss'
import './globals.scss'
import './utils.scss'
import './variables.scss'

import '@/styles/blocks/button.scss'
import '@/styles/blocks/case-studies.scss'
import '@/styles/blocks/footer.scss'
import '@/styles/blocks/header.scss'
import '@/styles/blocks/hero.scss'
import '@/styles/blocks/mark.scss'
import '@/styles/blocks/section.scss'
import '@/styles/blocks/services.scss'
