import 'normalize.css'
import '@/styles/fonts.scss'
import '@/styles/globals.scss'
import '@/styles/utils.scss'
import '@/styles/variables.scss'

import '@/styles/blocks/button.scss'
import '@/styles/blocks/accordion.scss'
import '@/styles/blocks/logo.scss'
import '@/styles/blocks/mark.scss'
import '@/styles/blocks/section.scss'
import '@/styles/blocks/slider.scss'

import '@/styles/blocks/header.scss'
import '@/styles/blocks/hero.scss'
import '@/styles/blocks/services.scss'
import '@/styles/blocks/case-studies.scss'
import '@/styles/blocks/our-working-process.scss'
import '@/styles/blocks/our-team.scss'
import '@/styles/blocks/testimonials.scss'
import '@/styles/blocks/contact-us.scss'
import '@/styles/blocks/footer.scss'
